### ISSUE TITLE
Manual Installation option / Okta sign-in widget CORS issues

### ISSUE THREAD

**Issue by bijanmmarkes** [oktadev/schematics#353]
Hi,

It seems that this plugin overwrites a lot of files and will actually corrupt a project in a sense if there is already an Okta configuration setup.

I believe this would be useful if rather than forcing the automation of file changes, to simply install all the required plugins needed, and to have documentation that points you in the right direction, as I'm going to have to do this manually by looking at the included files.

This seems like a great starting point for a fresh project, but for me with an existing project and routes/tabs, it will break my application.

Some people have to integrate this manually, so simply providing how to do that can save developers with existing configurations time and effort.

Great plugin, glad to see this exists and provides a clear way to integrate Okta authentication in PWAs.

**Comment by mraible** [comment]
@bijanmmarkes Thanks for your feedback. I originally created this project to help me show demos during presentations. I found there were a lot of steps required to integrate Okta into a brand new application, so I wanted to automate it. 

If you have an existing project, I think people can use each respective SDK's documentation to integrate Okta. Do you think that's a reasonable approach?

**Comment by bijanmmarkes** [comment]
@mraible Yes, I do believe so. I will be documenting my manual process for ionic/capacitor/angular, would you like me to contribute to the README or add a MANUAL_INSTALL.md type file?

I actually think the key to this is the following plugins:
 - ionic-appauth 
 - @ionic-native/secure-storage 
 - @ionic/storage

With that knowledge, and the changes to the info.plist, etc. Anyone could integrate it into their project.

Appreciate the research done on your end, as actual native functionality is always trickier than when testing in the browser.

**Comment by bijanmmarkes** [comment]
I believe a nice addition to this would be to utilize the environment files for passing clientId, etc. into the AuthService, rather than the hardcoded approach, but I understand this was just for demo purposes.

**Comment by mraible** [comment]
In my [React Native Login tutorial](https://developer.okta.com/blog/2019/11/14/react-native-login), I show how to integrate Okta (the easy way) with OktaDev Schematics. Then I show [the hard way](https://developer.okta.com/blog/2019/11/14/react-native-login#add-oidc-login-the-hard-way) without it. 

I neglected to show the hard way in my [Ionic tutorial](https://developer.okta.com/blog/2019/06/20/ionic-4-tutorial-user-authentication-and-registration), mostly because you have to create a lot of files. Ideally, I think these files should be provided by ionic-appauth, but that's not currently available. Do you think a new tutorial with Ionic "the hard way" would be useful?

**Comment by bijanmmarkes** [comment]
@mraible I truly do, because currently, I'm using the okta-angular-widget, and it seems to be causing issues for me. Do you know if the widget is supported for this type of flow?

**Comment by mraible** [comment]
We have an Okta Angular SDK and a Sign-In Widget. Are you talking about one of those projects? I've tried to make both of them work in Ionic and have NOT been successful. That's why this project uses Ionic AppAuth, which is based on [AppAuth JS](https://github.com/openid/AppAuth-JS).

**Comment by bijanmmarkes** [comment]
Yes, I'm using the okta signin-widget 

https://github.com/okta/okta-signin-widget

**Comment by mraible** [comment]
I have not figured out a way to authenticate with Okta without a redirect. If it were possible with our JavaScript SDKs, it’d be with our [Auth JS SDK](https://github.com/okta/okta-auth-js), which is the foundation for all our JavaScript SDKs. This library has recently been updated to [have React Native and Node.js support](https://github.com/okta/okta-auth-js#node-js-and-react-native-usage). It’s possible that it will work for your needs, but I’m not sure as I haven’t tried it myself.

The only other option I can think of would be to use our native iOS and/or Android SDKs to create a Cordova plugin that could talk directly to our authentication APIs. The downside of this is it might be tough to make it work when developing outside of an emulator and developing in an emulator would be a real pain for Ionic (IMO).

**Comment by mraible** [comment]
In [this blog post](https://developer.okta.com/blog/2017/08/22/build-an-ionic-app-with-user-authentication), I tried to use the Auth JS SDK and encountered issues.

> I believe this doesn’t work when the app is packaged with Cordova because it’s making a request to the server with an embedded iframe that then posts back to the current window using postMessage. It seems that Ionic/Cordova doesn’t support this flow (yet).

It's possible that using [Capacitor](https://capacitor.ionicframework.com/) can solve this, but not with it's current HTTP library + Okta. It sends a `capacitor://` scheme as an origin header and Okta only allows http/s for CORS.  

It looks like Capacitor's new HTTP library [hatched a testable version last week](https://github.com/ionic-team/capacitor/pull/2495#issuecomment-636209159). I haven't had a chance to try it myself. 

Currently, this project installs [Cordova Advanced HTTP](https://github.com/silkimen/cordova-plugin-advanced-http) for Capacitor projects.

**Comment by mraible** [comment]
I don't think you can change the Sign-In Widget to use the Advanced HTTP Plugin.

There's no specific reason I know of for not allowing `capacitor://`, but I don't think it's an issue since the new HTTP implementation in Capacitor will change it to use `http/s` like the Advanced HTTP Plugin.

**Comment by bijanmmarkes** [comment]
@mraible I wasn't aware that's what the plugin was for, thanks for pointing that out, I will try it out and report the results.

Thanks.

**Comment by bijanmmarkes** [comment]
@mraible Doesn't look like that plugin really did much, it seems more like it's meant to be used for manual HTTP requests rather than allowing to use a different schema.

Using the following capacitor config:
```
"server": {
    "iosScheme": "http",
    "androidScheme": "http",
    "allowNavigation": [
      "authorize.vta.org"
    ]
}
```
I am able to open authorize.vta.org in the app itself and redirect, but it doesn't set the cookie as depicted by the error below, and to me that's the same as opening another browser without the "open in app" popup that comes with it, preventing me from using the actual options I have set in my sign-in widget, or styling/native look and feel.


Error after redirect: `AuthSdkError: Unable to retrieve OAuth redirect params cookie`

I am using the Okta sign-in widget, which means I have no control over how to set the cookie, even if I were to use that authentication flow.

This is seeming to be a pretty big hack-around, and I think it can be resolved by simply allowing capacitor:// as a CORS origin, not sure if there will still be an issue with cookies in that case.

Do you have any examples of how this changes it to http/s? Am I missing something? Even with `"iosScheme": "http"` it still loads it as `capacitor://` Not sure if the plugin is meant to transform that or just give access to HTTP libraries natively.

**Comment by mraible** [comment]
> Do you have any examples of how this changes it to http/s? 

Sorry for the delay, I was on vacation in July. I don't have any examples, I just know that if you create a new Ionic app with Capacitor and use this project to install Okta support, it works.

**Comment by mraible** [comment]
Good news! We're working on adding support for `capacitor://localhost` as a trusted origin. Hopefully, this will make it so you can use SDKs with Ionic.

**Comment by mraible** [comment]
Better news! Someone figured out how to use capacitor-community/http and get the Sign-In Widget to work in an Ionic app on a device. https://github.com/capacitor-community/http/issues/45#issuecomment-786586655

**Comment by mraible** [comment]
Closing because I recommend redirecting to Okta over using the Sign-In Widget.
