### ISSUE TITLE
oktadev not working in cordova application

### ISSUE THREAD

**Issue by kuttimania** [oktadev/schematics#580]
I getting following error ,

Error: node_modules/capacitor-secure-storage-plugin/node_modules/@capacitor/core/types/definitions-internal.d.ts:16:18 - error TS2430: Interface 'CapacitorInstance' incorrectly extends interface 'CapacitorGlobal'.
Types of property 'Plugins' are incompatible.
Property 'SecureStoragePlugin' is missing in type '{ [pluginName: string]: { [prop: string]: any; }; }' but required in type 'PluginRegistry'.

16 export interface CapacitorInstance extends CapacitorGlobal {
~~~~~~~~~~~~~~~~~

node_modules/capacitor-secure-storage-plugin/dist/esm/definitions.d.ts:3:9
3 SecureStoragePlugin: SecureStoragePluginPlugin;
~~~~~~~~~~~~~~~~~~~
'SecureStoragePlugin' is declared here.

Error: src/app/app.module.ts:9:10 - error TS2305: Module '"../../node_modules/@ionic/storage/dist/esm"' has no exported member 'IonicStorageModule'.

9 import { IonicStorageModule } from '@ionic/storage';
~~~~~~~~~~~~~~~~~~

Error: ./src/app/app.module.ts 17:74-92
"export 'IonicStorageModule' was not found in '@ionic/storage'

Ionic Info;

Ionic:

Ionic CLI : 6.15.0
Ionic Framework : @ionic/angular 5.6.7
@angular-devkit/build-angular : 0.1102.13
@angular-devkit/schematics : 11.2.13
@angular/cli : 11.2.13
@ionic/angular-toolkit : 3.1.1

Utility:

cordova-res : not installed
native-run : not installed

System:

NodeJS : v14.17.0
npm : 6.14.13
OS : macOS Big Sur

**Comment by mraible** [comment]
You are correct. I just tried to create an app using Cordova and [these instructions](https://github.com/oktadev/schematics#ionic). It fails to startup with lots of compilation errors. I'll look into fixing it.

Just curious, why do you want to use Cordova instead of Capacitor? The Ionic folks seem to recommend Capacitor over Cordova.

**Comment by mraible** [comment]
Can you please try the latest release ([v4.1.2](https://github.com/oktadev/schematics/releases/tag/v4.1.2)) and see if it fixes it?

**Comment by kuttimania** [comment]
Still we are getting same error 
(base) kutti@init-mac-01 secure-ionic % ng add @oktadev/schematics --platform=cordova     
ℹ Using package manager: npm
✔ Found compatible package version: @oktadev/schematics@4.1.2.
✔ Package information loaded.

The package @oktadev/schematics@4.1.2 will be installed and executed.
Would you like to proceed? Yes
✔ Package successfully installed.


Error: node_modules/capacitor-secure-storage-plugin/node_modules/@capacitor/core/types/definitions-internal.d.ts:16:18 - error TS2430: Interface 'CapacitorInstance' incorrectly extends interface 'CapacitorGlobal'.
  Types of property 'Plugins' are incompatible.
    Property 'SecureStoragePlugin' is missing in type '{ [pluginName: string]: { [prop: string]: any; }; }' but required in type 'PluginRegistry'.

16 export interface CapacitorInstance extends CapacitorGlobal {
                    ~~~~~~~~~~~~~~~~~

  node_modules/capacitor-secure-storage-plugin/dist/esm/definitions.d.ts:3:9
    3         SecureStoragePlugin: SecureStoragePluginPlugin;
              ~~~~~~~~~~~~~~~~~~~
    'SecureStoragePlugin' is declared here.




** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

✔ Browser application bundle generation complete.

60 unchanged chunks

Build at: 2021-05-25T06:27:00.747Z - Hash: 5edcdb266b9fe0697903 - Time: 1267ms

Error: node_modules/capacitor-secure-storage-plugin/node_modules/@capacitor/core/types/definitions-internal.d.ts:16:18 - error TS2430: Interface 'CapacitorInstance' incorrectly extends interface 'CapacitorGlobal'.
  Types of property 'Plugins' are incompatible.
    Property 'SecureStoragePlugin' is missing in type '{ [pluginName: string]: { [prop: string]: any; }; }' but required in type 'PluginRegistry'.

16 export interface CapacitorInstance extends CapacitorGlobal {
                    ~~~~~~~~~~~~~~~~~

  node_modules/capacitor-secure-storage-plugin/dist/esm/definitions.d.ts:3:9
    3         SecureStoragePlugin: SecureStoragePluginPlugin;
              ~~~~~~~~~~~~~~~~~~~
    'SecureStoragePlugin' is declared here.

ionic info

Ionic:

   Ionic CLI                     : 6.15.0
   Ionic Framework               : @ionic/angular 5.6.7
   @angular-devkit/build-angular : 12.0.1
   @angular-devkit/schematics    : 11.2.13
   @angular/cli                  : 12.0.1
   @ionic/angular-toolkit        : 3.1.1

Utility:

   cordova-res : 0.15.3
   native-run  : not installed

System:

   NodeJS : v14.17.0 
   npm    : 6.14.13
   OS     : macOS Big Sur

**Comment by mraible** [comment]
Hmmm, it works for me. Can you please try the following:

```
rm -rf node_modules
rm package-lock.json
```

Then, create an `npm-shrinkwrap.json` file and add the following to it:

```
{
  "dependencies": {
    "capacitor-secure-storage-plugin": {
      "version": "0.4.0",
      "dependencies": {
        "@capacitor/core": {
          "version": "2.4.7"
        }
      }
    }
  }
}
```

Then, run `npm install` and `ionic serve` to see if it works.

**Comment by kuttimania** [comment]
It's working. Thanks
