### ISSUE TITLE
Firebase Deep link error

### ISSUE THREAD

**Issue by kuttimania** [oktadev/schematics#895]
Hi, 
When using cordova-plugin-firebasex plugin App not login.Getting error below 

**[FirebaseAnalytics][I-ACS023001] Deep Link does not contain valid required params. URL params: {
    code = "";
    state = ;
}**

"cordova-plugin-firebasex": "^14.1.0",
"@oktadev/schematics": "5.2.2",

Ionic:

   Ionic CLI                     : 6.19.0
   Ionic Framework               : @ionic/angular 6.1.6
   @angular-devkit/build-angular : 13.3.6
   @angular-devkit/schematics    : 13.3.6
   @angular/cli                  : 13.3.6
   @ionic/angular-toolkit        : 5.0.3

Cordova:

   Cordova CLI       : 11.0.0
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 13 other plugins)

Utility:

   cordova-res                          : 0.15.4
   native-run (update available: 1.6.0) : 1.5.0

System:

   Android SDK Tools : 26.1.1 
   ios-deploy        : 1.11.4
   ios-sim           : 8.0.2
   NodeJS            : v16.14.2 
   npm               : 8.5.0
   OS                : macOS Monterey
   Xcode             : Xcode 13.4.1 Build version 13F100

**Comment by mraible** [comment]
This seems to be related to Firebase, which this Schematic does not support. It's possible it will work, but I haven't made the time to investigate, nor do I plan to.
