### ISSUE TITLE
Angular Schematics dont produce compilable code

### ISSUE THREAD

**Issue by VRMink** [oktadev/schematics#903]
Due to the issue with the auth0 angular package, the schematics are not functional. Please see: https://github.com/auth0/auth0-angular/issues/255

**Comment by mraible** [comment]
Hello @VRMink.

Thanks for the bug report. I was on vacation for the month of July and missed it. I just upgraded this project to use Angular 14 in https://github.com/oktadev/schematics/pull/883. 

I tested Auth0 using the following command:

```
ng new angular-auth0 --routing --style css --strict
cd angular-auth0
npm install -D ../../oktadev*.tgz
schematics @oktadev/schematics:add-auth --issuer=$issuer --client-id=$clientId --auth0
```

Unit tests pass and I'm able to log in, so I'm closing this issue.
