### ISSUE TITLE
Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID

### ISSUE THREAD

**Issue by NatalieDinh** [oktadev/schematics#974]
Hello, 

I'm currently trying to run the `schematics @oktadev/schematics:add-auth` command on a React Native project.  However I receive an error: `Error: NOT SUPPORTED: keyword "id", use "$id" for schema ID`. This is about 3 steps into the follow guide: https://developer.okta.com/blog/2019/11/14/react-native-login, after installing the `oktadev/schematics` and the angular schematics CLI.

**Comment by mraible** [comment]
It should work if you use the latest version without a version.

```
npm i -D @oktadev/schematics
```

**Comment by mraible** [comment]
Closing due to lack of response. Please re-open if this is still an issue with the latest version.
